SHELL            := /bin/bash
ROOT_DIR         := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
BRICKLIB2_PATH   := $(realpath $(ROOT_DIR)/src/bricklib2)

include $(BRICKLIB2_PATH)/cmake/makefiles/Makefile_TNG.mk
